name = "cms-docs"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./public",entry-point = "workers-site"}
compatibility_date = "2022-03-17"
